### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/space-invaders#1]
Change style of game to improve the gameplay

**Comment by vanya-24** [comment]
Can you please provide more info about this project!

**Comment by vitobreda** [comment]
this is a simple game, i used basic css style so i want to improve that

**Comment by vitobreda** [comment]
> Can you please provide more info about this project!

this is a simple game, i used basic css style so i want to improve that.

**Comment by Shivangi-ch** [comment]
hi @vitobreda i will improve the ui of the game.
